CREATE TABLE IF NOT EXISTS `Users` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`username` VARCHAR(20) NOT NULL UNIQUE,
	`password` VARCHAR(20) NOT NULL,
	`email` VARCHAR(30) NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Orders` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`id_product` INTEGER NOT NULL UNIQUE,
	`user_id` INTEGER NOT NULL UNIQUE,
	`count` INTEGER NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `seller` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`company` VARCHAR(255) NOT NULL UNIQUE,
	`phone` VARCHAR(255) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS `products` (
	`id` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`cost` INTEGER NOT NULL CHECK(cost > 0),
	`count` INTEGER NOT NULL CHECK(count > 0),
	`seller_id` INTEGER NOT NULL UNIQUE,
	PRIMARY KEY(`id`)
);


ALTER TABLE `Orders`
ADD FOREIGN KEY(`id_product`) REFERENCES `products`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Orders`
ADD FOREIGN KEY(`user_id`) REFERENCES `Users`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `products`
ADD FOREIGN KEY(`seller_id`) REFERENCES `seller`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;